apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve
  namespace: kubeserve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: kubeserve
        image: kubeserve:1.0.0
        ports:
        - containerPort: 80
  