apiVersion: v1
kind: Service
metadata:
  name: kubeserve-service
  namespace: kubeserve
spec:
  selector:
    app: kubeserve
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 